version: '3.8'

services:
  library-app:
    image: library-app:latest
    ports:
      - "8081:8081"
    environment:
      API_BASE_URL: http://library-api:8080/
    depends_on:
      - mysql
      - redis
      - library-api
    networks:
      - library-network
    restart: on-failure:10

  library-api:
    image: library-api:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/librarydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysqlpassword
      
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      SPRING_BATCH_JDBC_INITIALIZE_SCHEMA: always
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: redispassword
      SPRING_REDIS_TIMEOUT: 2000
    depends_on:
      - mysql
      - redis
    networks:
      - library-network
    restart: on-failure:10
   
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_DATABASE: librarydb
    ports:
      - "3306:3306"
    networks:
      - library-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - library-network
    
networks:
  library-network:
    driver: bridge
  

